name: Release

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  build:
    name: Build - ${{ matrix.platform.target }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: windows-2025
            target: x86_64-pc-windows-msvc
            inno_arch: x64
          - os: windows-2025
            target: aarch64-pc-windows-msvc
            inno_arch: arm64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bins: cargo-zigbuild, cargo-deb, cargo-generate-rpm
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bins: cargo-zigbuild, cargo-deb, cargo-generate-rpm
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    env:
      PLATFORM_TARGET: ${{ matrix.platform.target }}
      PLATFORM_BINS: ${{ matrix.platform.bins }}
      INNO_ARCH: ${{ matrix.platform.inno_arch }}
      GLIBC_VERSION: 2.35
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        if: contains(matrix.platform.bins, 'cargo-zigbuild')
        with:
          use-cache: false

      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          targets: ${{ matrix.platform.target }}
          bins: ${{ matrix.platform.bins }}
          cache: false

      - name: Create release assets directory
        shell: pwsh
        run: New-Item -ItemType Directory -Path release-assets | Out-Null

      - name: Build binary
        shell: bash
        run: |
          if [[ "$PLATFORM_BINS" == *"zigbuild"* ]]; then
            cargo zigbuild --target "${PLATFORM_TARGET}.${GLIBC_VERSION}" --release --locked
          else
            cargo build --target "$PLATFORM_TARGET" --release --locked
          fi

      - name: Create Deb package
        if: contains(matrix.platform.bins, 'cargo-deb')
        shell: pwsh
        run: |
          $nightly = if ($env:GITHUB_EVENT_NAME -eq 'schedule') { "--deb-version=2.nightly" } else { "" }
          cargo deb --target $env:PLATFORM_TARGET --output release-assets/ --no-build --no-strip $nightly

      - name: Create RPM package
        if: contains(matrix.platform.bins, 'cargo-generate-rpm')
        shell: pwsh
        run: |
          if ($env:GITHUB_EVENT_NAME -eq 'schedule') {
            cargo generate-rpm --target $env:PLATFORM_TARGET --output release-assets/ --set-metadata='version="nightly"'
          } else {
            cargo generate-rpm --target $env:PLATFORM_TARGET --output release-assets/
          }

      - name: Rename binary
        id: rename_binary
        shell: pwsh
        run: |
          $bin = if ($env:RUNNER_OS -eq 'Windows') { "komac.exe" } else { "komac" }
          if ($env:GITHUB_EVENT_NAME -eq 'schedule') {
            $newName = "komac-nightly-$env:PLATFORM_TARGET"
          } else {
            $newName = "komac-$($env:GITHUB_REF_NAME.TrimStart('v'))-$env:PLATFORM_TARGET"
          }
          if ($env:RUNNER_OS -eq 'Windows') {
            $newName += ".exe"
            Move-Item -Path "target/$env:PLATFORM_TARGET/release/$bin" -Destination "release-assets/$newName"
          }
          "name=$newName" >> $env:GITHUB_OUTPUT

      - name: Create Tar archive
        if: ${{ runner.os != 'Windows' }}
        env:
          RENAMED_BINARY: ${{ steps.rename_binary.outputs.name }}
        run: |
          tar -cvf "release-assets/${RENAMED_BINARY}.tar.gz" \
            --use-compress-program="gzip -9" \
            -C "target/${PLATFORM_TARGET}/release" komac \
            -C ../../../ LICENSE.md

      - name: Create Inno Installer
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        env:
          RENAMED_BINARY: ${{ steps.rename_binary.outputs.name }}
        run: |
          winget install --exact JRSoftware.InnoSetup --scope machine --silent --accept-package-agreements --accept-source-agreements --disable-interactivity
          $input = "../../release-assets/$env:RENAMED_BINARY"
          $output = (Resolve-Path "release-assets").Path
          $outputName = ($env:RENAMED_BINARY -replace '\.exe$', '').Replace("komac", "komac-setup")
          & "${env:ProgramFiles(x86)}\Inno Setup 6\iscc.exe" assets/inno/installer.iss `
            /DInputExecutable=$input `
            /DArchitecture=$env:INNO_ARCH `
            /O$output `
            /F$outputName

      - name: Upload release assets
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: release-assets-${{ matrix.platform.target }}
          path: release-assets/
          if-no-files-found: error

  publish-release:
    name: Create or update release
    needs: build
    runs-on: ubuntu-slim
    permissions:
      contents: write # GitHub release publish
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: release-assets-*
          path: release-assets
          merge-multiple: true

      - name: Compute SHA256SUMS
        run: |
          cd release-assets
          sha256sum --binary -- * > SHA256SUMS
          cat SHA256SUMS

      - name: Create or update release
        shell: bash
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" ]]; then
            tag="nightly"
            gh release upload "$tag" release-assets/* --clobber
          else
            tag="$GITHUB_REF_NAME"
            gh release create "$tag" release-assets/* \
              --draft \
              --generate-notes \
              --verify-tag
          fi
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
